In [188]:
import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [189]:
df = pd.read_csv("brain_stroke.csv")
dfr = pd.read_csv("brain_stroke_rusak.csv")

In [190]:
df

gender   age  hypertension  heart_disease ever_married      work_type  \
0       Male  67.0             0              1          Yes        Private   
1       Male  80.0             0              1          Yes        Private   
2     Female  49.0             0              0          Yes        Private   
3     Female  79.0             1              0          Yes  Self-employed   
4       Male  81.0             0              0          Yes        Private   
...      ...   ...           ...            ...          ...            ...   
4976    Male  41.0             0              0           No        Private   
4977    Male  40.0             0              0          Yes        Private   
4978  Female  45.0             1              0          Yes       Govt_job   
4979    Male  40.0             0              0          Yes        Private   
4980  Female  80.0             1              0          Yes        Private   

     Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0             Urban             228.69  36.6  formerly smoked       1  
1             Rural             105.92  32.5     never smoked       1  
2             Urban             171.23  34.4           smokes       1  
3             Rural             174.12  24.0     never smoked       1  
4             Urban             186.21  29.0  formerly smoked       1  
...             ...                ...   ...              ...     ...  
4976          Rural              70.15  29.8  formerly smoked       0  
4977          Urban             191.15  31.1           smokes       0  
4978          Rural              95.02  31.8           smokes       0  
4979          Rural              83.94  30.0           smokes       0  
4980          Urban              83.75  29.1     never smoked       0  

[4981 rows x 11 columns]

In [191]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4981 entries, 0 to 4980
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   gender             4981 non-null   object 
 1   age                4981 non-null   float64
 2   hypertension       4981 non-null   int64  
 3   heart_disease      4981 non-null   int64  
 4   ever_married       4981 non-null   object 
 5   work_type          4981 non-null   object 
 6   Residence_type     4981 non-null   object 
 7   avg_glucose_level  4981 non-null   float64
 8   bmi                4981 non-null   float64
 9   smoking_status     4981 non-null   object 
 10  stroke             4981 non-null   int64  
dtypes: float64(3), int64(3), object(5)
memory usage: 428.2+ KB


In [192]:
df.shape

(4981, 11)

# Training set 70 : Testing set 30

In [193]:
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]

In [194]:
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.3)

In [195]:
print("Dimensi X_train : ", X_train.shape)
print("Dimensi X_train : ", X_test.shape)
print("Dimensi y_train : ", y_train.shape)
print("Dimensi y_test : ", y_test.shape)

Dimensi X_train :  (3486, 10)
Dimensi X_train :  (1495, 10)
Dimensi y_train :  (3486,)
Dimensi y_test :  (1495,)


# Normalisasi

In [196]:
dAngka = df["age"].astype("float64")*0.001
dAngka

0       0.067
1       0.080
2       0.049
3       0.079
4       0.081
        ...  
4976    0.041
4977    0.040
4978    0.045
4979    0.040
4980    0.080
Name: age, Length: 4981, dtype: float64

In [197]:
mm = MinMaxScaler()
x_scaled = mm.fit_transform(
df[['bmi']])

In [198]:
normalisasi = pd.DataFrame(x_scaled)
normalisasi.head(6)

0
0  0.647564
1  0.530086
2  0.584527
3  0.286533
4  0.429799
5  0.383954

# Standardisasi

In [199]:
ss = StandardScaler()
data = np.asarray(df[["age", "bmi", "hypertension"]])
Scaled_data = ss.fit_transform(data)

In [200]:
print("Nilai Data Sebelum scaling : ") 
print(data) 
print("Nilai standar deviasi: ", np.std(data))
print("============================================")
print("\n Nilai Data setelah scaling : ") 
print(Scaled_data) 
print("Nilai standar deviasi: ", np.std(Scaled_data)) 

Nilai Data Sebelum scaling : 
[[67.  36.6  0. ]
 [80.  32.5  0. ]
 [49.  34.4  0. ]
 ...
 [45.  31.8  1. ]
 [40.  30.   0. ]
 [80.  29.1  1. ]]
Nilai standar deviasi:  22.57168694633216

 Nilai Data setelah scaling : 
[[ 1.04058433  1.19323816 -0.32618577]
 [ 1.61427033  0.58938961 -0.32618577]
 [ 0.24624988  0.86922187 -0.32618577]
 ...
 [ 0.06973111  0.48629352  3.06573766]
 [-0.15091734  0.22118927 -0.32618577]
 [ 1.61427033  0.08863715  3.06573766]]
Nilai standar deviasi:  0.9999999999999999


# Membuat Null
karena di dalam dataset tidak ada nilai null maka kita buat dulu

In [234]:
df.iloc[3,2] = np.nan

In [235]:
df

gender   age  hypertension  heart_disease ever_married      work_type  \
0       Male  67.0           0.0            1.0          Yes        Private   
1       Male  80.0           0.0            1.0          Yes        Private   
2     Female  49.0           0.0            0.0          Yes        Private   
3        NaN  79.0           NaN            NaN          Yes  Self-employed   
4       Male  81.0           0.0            0.0          Yes        Private   
...      ...   ...           ...            ...          ...            ...   
4976    Male  41.0           0.0            0.0           No        Private   
4977    Male  40.0           0.0            0.0          Yes        Private   
4978  Female  45.0           1.0            0.0          Yes       Govt_job   
4979    Male  40.0           0.0            0.0          Yes        Private   
4980  Female  80.0           1.0            0.0          Yes        Private   

     Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0             Urban             228.69  36.6  formerly smoked     1.0  
1             Rural             105.92  32.5     never smoked     1.0  
2             Urban             171.23  34.4           smokes     1.0  
3             Rural                NaN  24.0     never smoked     NaN  
4             Urban             186.21  29.0  formerly smoked     1.0  
...             ...                ...   ...              ...     ...  
4976          Rural              70.15  29.8  formerly smoked     0.0  
4977          Urban             191.15  31.1           smokes     0.0  
4978          Rural              95.02  31.8           smokes     0.0  
4979          Rural              83.94  30.0           smokes     0.0  
4980          Urban              83.75  29.1     never smoked     0.0  

[4981 rows x 11 columns]

# Data Cleaning

In [236]:
df.isna().sum()

gender               1
age                  0
hypertension         1
heart_disease        1
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    1
bmi                  0
smoking_status       0
stroke               1
dtype: int64

# Mengubah nilai null yang bertipe data desimal

In [238]:
imputer = SimpleImputer(strategy = 'mean')
df["avg_glucose_level"] = imputer.fit_transform(df[["avg_glucose_level"]])
df["heart_disease"] = imputer.fit_transform(df[["heart_disease"]])
print("Jumlah null : ")
print(df.isna().sum())

Jumlah null : 
gender               1
age                  0
hypertension         1
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               1
dtype: int64


# Mengubah nilai null yang bertipe data kategorikal

In [239]:
imputer = SimpleImputer(strategy = 'most_frequent')
df["gender"] = imputer.fit_transform(df[["gender"]])
print("Jumlah null : ")
print(df.isna().sum())

Jumlah null : 
gender               0
age                  0
hypertension         1
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               1
dtype: int64


# Mengubah nilai null yang bertipe data bilang bulat

In [241]:
imputer = SimpleImputer(strategy = 'most_frequent')
df["hypertension"] = imputer.fit_transform(df[["hypertension"]])
df["stroke"] = imputer.fit_transform(df[["stroke"]])
print("Jumlah null : ")
print(df.isna().sum())

Jumlah null : 
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64


# Data yang Terduplikat
Karena di dalam data tidak ada nilai yang duplikat, dan saya tidak mengerti bgmn cara untuk membuat nilai dalam data terduplikat jadi saya langsung masukkan saja cara untuk menghilangkan duplikatnya

In [207]:
dfr[dfr.duplicated()]

Empty DataFrame
Columns: [gender, age, hypertension, heart_disease, ever_married, work_type, Residence_type, avg_glucose_level, bmi, smoking_status, stroke]
Index: []

In [208]:
df.drop_duplicates(inplace=True)

In [209]:
print("Nilai Duplikat:",df.duplicated().sum())

Nilai Duplikat: 0


# Mengubah tipe data angka

In [210]:
encoder = OrdinalEncoder() 
dfr["bmiENC"] = encoder.fit_transform(dfr[["gender"]]) 
dfr.head()

gender   age  hypertension  heart_disease ever_married      work_type  \
0    Male  67.0           0.0            1.0          Yes        Private   
1    Male  80.0           0.0            1.0          Yes        Private   
2  Female  49.0           0.0            0.0          Yes        Private   
3  Female  79.0           0.0            0.0          Yes  Self-employed   
4    Male  81.0           0.0            0.0          Yes        Private   

  Residence_type  avg_glucose_level   bmi   smoking_status  stroke  bmiENC  
0          Urban             228.69  36.6  formerly smoked       1     1.0  
1          Rural             105.92  32.5     never smoked       1     1.0  
2          Urban             171.23  34.4           smokes       1     0.0  
3          Rural             174.12  24.0     never smoked       1     0.0  
4          Urban             186.21  29.0  formerly smoked       1     1.0

In [211]:
dfr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4981 entries, 0 to 4980
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   gender             4981 non-null   object 
 1   age                4981 non-null   float64
 2   hypertension       4981 non-null   float64
 3   heart_disease      4981 non-null   float64
 4   ever_married       4981 non-null   object 
 5   work_type          4981 non-null   object 
 6   Residence_type     4981 non-null   object 
 7   avg_glucose_level  4981 non-null   float64
 8   bmi                4981 non-null   float64
 9   smoking_status     4981 non-null   object 
 10  stroke             4981 non-null   int64  
 11  bmiENC             4981 non-null   float64
dtypes: float64(6), int64(1), object(5)
memory usage: 467.1+ KB


# One Hot Encoding

In [212]:
encoder = OneHotEncoder(sparse=False) 
bmiEnc = encoder.fit_transform(dfr[["bmi"]]) 
bmiEnc = pd.DataFrame(bmiEnc) 
dfr = dfr.join(bmiEnc) 
dfr 

gender   age  hypertension  heart_disease ever_married      work_type  \
0       Male  67.0           0.0            1.0          Yes        Private   
1       Male  80.0           0.0            1.0          Yes        Private   
2     Female  49.0           0.0            0.0          Yes        Private   
3     Female  79.0           0.0            0.0          Yes  Self-employed   
4       Male  81.0           0.0            0.0          Yes        Private   
...      ...   ...           ...            ...          ...            ...   
4976    Male  41.0           0.0            0.0           No        Private   
4977    Male  40.0           0.0            0.0          Yes        Private   
4978  Female  45.0           1.0            0.0          Yes       Govt_job   
4979    Male  40.0           0.0            0.0          Yes        Private   
4980  Female  80.0           1.0            0.0          Yes        Private   

     Residence_type  avg_glucose_level   bmi   smoking_status  ...  332  333  \
0             Urban             228.69  36.6  formerly smoked  ...  0.0  0.0   
1             Rural             105.92  32.5     never smoked  ...  0.0  0.0   
2             Urban             171.23  34.4           smokes  ...  0.0  0.0   
3             Rural             174.12  24.0     never smoked  ...  0.0  0.0   
4             Urban             186.21  29.0  formerly smoked  ...  0.0  0.0   
...             ...                ...   ...              ...  ...  ...  ...   
4976          Rural              70.15  29.8  formerly smoked  ...  0.0  0.0   
4977          Urban             191.15  31.1           smokes  ...  0.0  0.0   
4978          Rural              95.02  31.8           smokes  ...  0.0  0.0   
4979          Rural              83.94  30.0           smokes  ...  0.0  0.0   
4980          Urban              83.75  29.1     never smoked  ...  0.0  0.0   

      334  335  336  337  338  339  340  341  
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...   ...  ...  ...  ...  ...  ...  ...  ...  
4976  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4977  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4978  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4979  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4980  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[4981 rows x 354 columns]